/// Flutter icons Dangericon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
//    fonts:
//     - family:  Dangericon
//       fonts:
//        - asset: fonts/Dangericon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Dangericon {
  Dangericon._();

  static const _kFontFam = 'Dangericon';
  static const String? _kFontPkg = null;

  static const IconData logobackground = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
